# Generated by Django 4.2.3 on 2023-07-05 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата удаления'),
        ),
        migrations.AddField(
            model_name='artist',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='дата удаления')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('followers', models.PositiveIntegerField(default=0, verbose_name='фоловеры')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.band', verbose_name='группа'),
        ),
    ]
