# Generated by Django 4.2.3 on 2023-07-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_song_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={},
        ),
        migrations.AlterField(
            model_name='band',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.country', verbose_name='страна'),
        ),
    ]
