# Generated by Django 4.2.3 on 2023-07-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_band_options_alter_band_country'),
        ('main', '0014_alter_song_duration'),
    ]

    operations = [
    ]
